server:
  port : 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always       
      enabled: true
    info:
      enabled: true
  info:
    defaults:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
  health:
    diskspace:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  application:
    name: FINANCE
  profiles:
    active: Accountant

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    allow-redirects: true
  instance:
    hostname: localhost
              
info:
  name: ${spring.application.name}
  description: Employee Finance Management
  environment: ${spring.profiles.active}
  version: 0.0.1



logging:
  file: E:/ems-logs/finance.log